name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: pro

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Deploy application
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh_key.pem
          chmod 600 ~/.ssh/ssh_key.pem
          ssh -i ~/.ssh/ssh_key.pem -o StrictHostKeyChecking=no "$REMOTE_USER@$REMOTE_HOST" "bash -s" < deploy.sh
        env:
          SSH_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_USER: ${{ secrets.REMOTE_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
